version: '3'

services:
  php:
    build: ./docker/php
    env_file:
      - .env
    volumes:
      - ./docker/log:/var/log/container
      - ./app_php:/app
    expose:
      - 9005
    depends_on:
      - postgres
      - redis
    restart: on-failure

  python:
    env_file:
      - .env
    build: ./docker/python
    volumes:
      - ./docker/log:/var/log/container
      - ./docker/data:/data
      - ./app_python:/app
    depends_on:
      - postgres
      - redis
    restart: on-failure

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./docker/log:/var/log/container
      - ./docker/postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: on-failure

  nginx:
    image: nginx:latest
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app_php:/app
      - ./docker/log:/var/log/container
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq
    expose:
      - 15672
      - 15671
    ports:
      - "5673:5672"
      - "15672:15672"
    restart: on-failure

  redis:
    image: redis:latest
    env_file:
      - .env
    expose:
      - 6379
    ports:
      - "6379:6379"
    restart: on-failure

